/*
native SendInfoMessage(playerid, type 0: Error | 1: Ayuda | 2: Info | 3: Importante, const optional[], const message[]);
native SendSyntaxError(playerid, const command[], const example[]);
native SendAccessError(playerid, const command[]);
native SendAdviseMessage(playerid, const advise[]);
native IsPlayerLogued(playerid);
native IsPlayerLoguedEx(playerid, playeridCheck);
native IsPlayerNear(playerid, playeridCheck);
native Acciones(playerid, type 0: Me | 1: Ame | 2: Intentar Ok | 3: Intentar Roj | 4..., const text[]);
*/
