#define DIR_FACCIONES "facciones"
#define MAX_FACCION_NAME       				30
#define MAX_FACCION_COUNT      				25
#define MAX_FACCION_RANGOS                  10
#define MAX_FACCION_SKIN                    15
#define MAX_ALMACENES                       3
#define CIVIL			0
#define GOBIERNO  		1
#define LICENCIEROS		2
#define TRAFICANTES     3
#define LCN             4
#define YKZ             5
#define TAXI            6
#define SFPD            7
#define NFS             8
#define SFMD            9
#define CNN             10
#define ADP             11
#define CAMIONEROS      12
#define TALLER_SF       13
#define LSPD            14
#define CONTRABANDISTAS 15
#define SICARIOS        16
#define TALLER_LS       17
#define COLTS	        18
#define AK		        19
#define VELTRAN         20
#define HEORS           21
#define LSMD            22
#define MAX_FACCION    LSMD