#define MAX_HOUSE_COUNT 401

#define MAX_HOUSE_FRIENDS 5

#define DIR_HOUSES "houses"
#define DIR_HOUSES_WEAPONS ""DIR_HOUSES"_weapons"
#define DIR_HOUSES_FRIENDS ""DIR_HOUSES"_friends"
#define MAX_HOUSE_PICKUP_DISTANCE 100.0
#define PICKUP_MODEL_CASA_FOR_SALE 1273
#define PICKUP_MODEL_CASA_SOLD 19522
#define PICKUP_MODEL_CASA_RENT 19523

#define MAX_HOUSE_TYPE_COUNT 40

#define MAX_GARAGE_TYPE_COUNT 40
#define PICKUP_MODEL_GARAGE_CASA_VEHICLE 19134
#define PICKUP_MODEL_GARAGE_CASA_ON_FOOT 19133

#define DIR_HOUSES_GARAGES ""DIR_HOUSES"_garages"

#define MAX_GARAGE_FOR_HOUSE 5
#define MAX_GARAGES_DESING MAX_GARAGE_FOR_HOUSE

#define MAX_REFRIGERADOR_SLOTS_COUNT 10

#define DIR_HOUSES_FRIDGE ""DIR_HOUSES"_fridge"